### ISSUE TITLE
EPIC: Improve functionality of current site design

### ISSUE THREAD

**Issue by moxiegirl** [docker/docs-base#106]
* [ ] Improve indentation and syntax highlight in code blocks https://github.com/docker/docs-base/issues/89
* [ ] Fix relative links when page ends in slash https://github.com/docker/docs-base/issues/88
* [ ] Favicon i s not set properly https://github.com/docker/docs-base/issues/84
* [ ] Improve color/font design for readability https://github.com/docker/docs-base/issues/69
* [ ] Implement site-wide header-footer as provided by www https://github.com/docker/docs-base/issues/51
* [ ] Headers broken by transformation of -- https://github.com/docker/docs-base/issues/66
